version: '3.5'
services:
  ruby:
    image: webhook/ruby:dev
    container_name: webhook_ruby
    volumes:
      - ${pwd}/code/src:/code/src
    working_dir: /code/src
    entrypoint: ruby /code/src/GBA_Pong_webhook.rb p ENV["API_KEY"]
    ports:
      - '4567:4567'

  php:
    image: webhook/php:dev
    container_name: webhook_php
    volumes:
       - ${pwd}/code/src/artifacts:/var/www/html
    working_dir: /var/www/html
    entrypoint: php -S 0.0.0.0:80 -t /var/www/html
    ports:
      - '80:80'