version: '3.5'
services:
  ruby:
    image: webhook/ruby:dev
    container_name: webhook_ruby
    volumes:
      - ${pwd}/code/src:/code/src
      - ${pwd}/.env_prd:/.env_prd
    working_dir: /code/src
    entrypoint: sh -c "chmod +x run.sh && ./run.sh"
    ports:
      - '4567:4567'
